name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build Docker
    runs-on: host

    steps:
      - uses: actions/checkout@v4
      - run : docker build -f Dockerfile -t registry.danielsplaygrounds.com/docker/images/tms_web:latest . 
  deploy:
    needs:
      - build
    name: Push Docker
    runs-on: host
    steps:
      - run : docker push registry.danielsplaygrounds.com/docker/images/tms_web:latest    