name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Build and analyze
    runs-on: host
    
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - run: "sonar \
              -Dsonar.host.url=https://sonarqube.danielsplaygrounds.com \
              -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.pullrequest.key=${{ github.head_ref }} \
              -Dsonar.pullrequest.branch= ${{ github.head_ref }} \
              -Dsonar.pullrequest.base=master
              -Dsonar.projectKey=tmsweb"  